baseURL = "/"
languageCode = "en-us"
title = "Fluentbit, High Performance"


[params]
email = ""
logo = "/images/logo.svg"
logo2 = "/images/logo-white.svg"
footer_logo = "/images/footer-logo.svg"
copyright = "© 2022 Fluent Bit. All rights reserved"
lastVersion = "v1.8.12"
releasedOn = "Jan 24, 2022"
	         	         
   [menu]
    [[menu.main]]
        identifier = "documentation"
        url = "https://docs.fluentbit.io/manual"
        name = "DOCUMENTATION"
        weight = 1
        tab = "extranal" 
    [[menu.main]]
        identifier = "how it works"
        url = "/how-it-works/"
        name = "how it works"
        weight = 2
    [[menu.main]]
        identifier = "release notes"
        url = "/announcements/"
        name = "RELEASE NOTES"
        weight = 3    
    [[menu.main]]
        identifier = "Enterprise"
        url = "/enterprise/"
        name = "Enterprise"
        weight = 4    
    [[menu.main]]
        identifier = "Community"
        url = "/community/"
        name = "Community"
        weight = 5 
    [[menu.main]]
        identifier = "blog"
        url = "/blog/"
        name = "Blog"
        weight = 7   

    [[menu.main]]
        identifier = "slack"
        url = "https://launchpass.com/fluent-all"
        name = "slack"
        weight = 8
        pre = "/images/slack.svg"
        slack = "/images/slack-w.svg"

    
    [params.latestVer]
    light = "true"
    heading = "Fluent Bit v1.8.12 is out!"
    subHeading = "New release on Jan 24, 2022,"
    text = "Check out the Release Notes, read the Updated Documentation or jump directly to the Downloads Section."
    smallText = "We are part of a wide community, <strong>no vendor lock-in.</strong>"
    btnText = "Download Now"
    btnUrl = "https://docs.fluentbit.io/manual/installation/getting-started-with-fluent-bit"
    bottomText = ":: Read Documentation"
    bottomUrl = "https://docs.fluentbit.io/manual/"

    
    [[params.footer.bottom]]
        url = "#"
        name = "Terms & Conditions"
        weight = 1
    [[params.footer.bottom]]
        url = "#"
        name = "Privacy Policy"
        weight = 2
    [[params.footer.bottom]]
        url = "#"
        name = "Sitemap"
        weight = 3
    [[params.footer.bottom]]
        url = "#"
        name = "Disclaimer"
        weight = 4

 [[params.social]]
    url   = "https://launchpass.com/fluent-all"
    icon  = "/images/slack-color.svg" 
    name = "slack"
 [[params.social]]
    url   = "https://twitter.com/fluentbit"
    icon  = "/images/twitter-color.svg" 
    name = "twitter"
#  [[params.social]]
#     url   = "https://www.youtube.com/results?search_query=fluentbit"
#     icon  = "fa fa-youtube-play" 
#     name = "youtube"



[permalinks]
    posts = "blog/:year/:month/:day/:title/"
    # posts = "blog/:title/"
    pages = ":slug/"





[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]


  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ''
    footnoteReturnLinkContents = ''
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = true
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
    extensions = ["hardLineBreak"]

  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = '2 3'
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'api' 
    tabWidth = 20
    # style= 'monika api fruity monokai native paraiso-dark rrt solarized-dark solarized-dark256 swapoff vim'

  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2
  
  [markup.goldmark.renderer]
    unsafe= true

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = "title"
    weight = 30

  [[related.indices]]
    name = "description"
    weight = 30

  [[related.indices]]
    name = "tags"
    weight = 30

  [[related.indices]]
    name = "date"
    weight = 10
